name: Deploy to FTP

on:
  repository_dispatch:
    types: [deploy-ftp-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout different repository
        uses: actions/checkout@v3
        with:
          repository: zarichniuk/sezam4mam
          token: ${{ github.event.client_payload.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build

      - name: Echo directory contents
        run: ls -la ./dist

      - name: Run a script
        run: echo "Done."
